"""Adiciona campo de imagem ao Cupcake

Revision ID: 0d6dada0e1dd
Revises: 3
Create Date: 2025-05-03 14:38:40.012440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6dada0e1dd'
down_revision = '3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupcake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupcake', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
