"""empty message

Revision ID: 1be3a1f3964f
Revises: 4a99a69b285f
Create Date: 2025-05-07 23:11:28.888359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be3a1f3964f'
down_revision = '4a99a69b285f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('number')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
