"""Add FavoriteCupcake model

Revision ID: 3
Revises: 2
Create Date: 2024-11-27 20:33:52.409924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_cupcake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cupcake_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupcake_id'], ['cupcake.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_cupcake')
    # ### end Alembic commands ###
